platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatCamp Demo' do
    #pod 'ChatCampUIKit'
    pod 'ChatCampUIKit'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "SwiftyCam"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.3'
            end
        end
    end
end
