platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatCamp Demo' do
    pod 'ChatCampUIKit', :path => '/Users/saurabh/Desktop/Developer/chatcamp/ChatCampUIKit'
end
